### PR TITLE
Added custom build instructions to the docker deployment docs

### PR DESCRIPTION
**Pull request by joshuacox**
I answered someone this morning in the gitter.im chat and realized there was not a good explanation of this in the docs.

### CODE REVIEW

**Comment by joshuacox** [comment]
I hesitate to include the secion on `reaction deploy` as I have not used this method yet, but I know that is the end goal with the reaction as SaaS

**Comment by joshuacox** [comment]
changed base to marketplace

**Comment by joshuacox** [comment]
yikes sorry @machikoyasuda  I came in from the marketplace  branch, and thought I had mistakenly come wrong, and switched the branch back.  If you like, I can rebase from whatever branch you want.

**Comment by machikoyasuda** [comment]
@joshuacox Rebase would be great! We're in the middle of changing some base branch stuff around. I would recommend making a PR into `master` from here on out.

**Comment by machikoyasuda** [comment]
PS. Thanks for contributing! @jshimko and I will be reviewing this.

**Comment by joshuacox** [comment]
closing as this became messy, continue in #270

**Pull request closed without merging**
