### PR TITLE
Add documentation for the geotagging-extension of example-plugin

### PR DESCRIPTION
**Pull request by prinzdezibel**
This PR adds documentation for the geotagging-extension that is part of the reaction-example-plugin.

It accompanies the following PR in reaction-example-plugin:
reactioncommerce/reaction-example-plugin#22

### CODE REVIEW

**Comment by prinzdezibel** [comment]
Notice: This PR also includes older PR's which are not approved yet. This is just because this PR really is **dependent** on the other PRs to work properly.

**Comment by machikoyasuda** [comment]
This looks great so far!

One formatting suggestion: The tutorial should have numbered steps, like this:

1. Add xyz to this file.

<explanation goes here>

2. Refresh the browser and you should see this...

That format makes it easier to read!

**Comment by prinzdezibel** [comment]
@machikoyasuda Ok, I've introduced the numbering for each section. Is that what you've meant or were you thinking about some specific part in the tutorial?

**Comment by machikoyasuda** [comment]
I like it! THanks

**Comment by prinzdezibel** [comment]
@zenweasel Could you take over and merge if ok from your side? (Depends on the other PR in example-plugin)

**Pull request merged**
