### PR TITLE
updated screenshots

### PR DESCRIPTION
**Pull request by sophiehe**
updated images for reaction docs

### CODE REVIEW

**Comment by aaronjudd** [comment]
We should be using a generic login for the screenshots (these all have your name in them..) You can set this up in using instructions from https://docs.reactioncommerce.com/reaction-docs/master/configuration.

If you use "admin@ongoworks.com" as the email, and "Admin" as the user name,  the gravatar will already be configured to be the Reaction logo.

**Comment by aaronjudd** [comment]
@sophiehe do you want to update these images or should I close this PR?

**Comment by aaronjudd** [comment]
@saralouhicks these screenshots ok for now?

**Comment by saralouhicks** [comment]
No, let's close this. @sophiehe - Let's update the screenshots to use a generic login name and also use product images that are ours (Reaction t-shirts). Thx!

**Pull request closed without merging**
