### PR TITLE
Remove references to repos that were folded into Reaction

### PR DESCRIPTION
**Pull request by zenweasel**

### CODE REVIEW

**Comment by zenweasel** [comment]
@machikoyasuda Any reason not to merge this?

**Comment by aaronjudd** [comment]
actually might have been.. we still merging to `development`?

**Comment by machikoyasuda** [comment]
@aaronjudd @zenweasel I suppose this will be officially the last PR to merge into dev :) Will deprecate the branch tomorrow first thing!

**Comment by zenweasel** [comment]
Hmmm, I guess that makes sense. DIdn't even occur to me honestly.

**Comment by aaronjudd** [comment]
Merged to master manually.

**Comment by aaronjudd** [comment]
@machikoyasuda I sort of jumped the gun for you, may have made matters worse, lol. ping me in the am if we need to fix anything.

**Pull request merged**
