### PR TITLE
Add FAQ: How to create a custom homepage

### LINKED ISSUE #425: [Developer FAQ] How to do I create a custom home page?

### PR DESCRIPTION
**Pull request by prinzdezibel**
Closes #425

- Move explanation on this topic to an own, dedicated page (away from
page layout)
- Encourage to create a plugin instead of putting stuff into /custom
- use new React way of extending components via registerComponent

NOTE: This PR depends on https://github.com/reactioncommerce/reaction/pull/3524
which is currently in release-1.8.0

It won't work if applied to current master.

### CODE REVIEW

**Comment by machikoyasuda** [comment]
Just a few lint errors!

```

developer/how-to-create-a-custom-homepage.md
          4:1  warning  Remove 1 line before node                      no-consecutive-blank-lines  remark-lint
         16:1  warning  Remove 1 line before node                      no-consecutive-blank-lines  remark-lint
         47:1  warning  Remove 2 lines before node                     no-consecutive-blank-lines  remark-lint
         55:1  warning  Remove 1 line before node                      no-consecutive-blank-lines  remark-lint
  56:32-56:53  warning  Don’t use literal URLs without angle brackets  no-literal-urls             remark-lint
         60:1  warning  Remove 1 line before node                      no-consecutive-blank-lines  remark-lint
  73:18-73:49  warning  Don’t use literal URLs without angle brackets  no-literal-urls             remark-lint
```

**Comment by prinzdezibel** [comment]
Thanks, @machikoyasuda

**Comment by machikoyasuda** [comment]
The content looks great! I definitely agree with the idea of breaking it up into its own tutorial.

Let's clean up the style for readability.

I would like the tutorial to have the same markdown style as this one: https://docs.reactioncommerce.com/reaction-docs/master/how-to-change-the-favicon

You can compare the two side by side:

https://docs.reactioncommerce.com/reaction-docs/docs-425-prinzdezible-how-to-create-custom-home-page/how-to-create-a-custom-homepage and https://docs.reactioncommerce.com/reaction-docs/master/how-to-change-the-favicon

screen shot 2018-02-13 at 4 14 33 pm

The main two things to change:
1. Change the title to `# Tutorial: Create a custom home page`
2. Change the numbered steps to `## Step 1: xxx` and the explanation as regular text. Example:

```
# Step 1. Create a new custom plugin

Use the `reaction plugins create` command to create a plugin called `custom-home`.

(code snippet)
```

```
# Step 2. Set up a `default.js` file:

Create a file called `default.js` in the `/imports/plugins/custom/custom-home/client/` folder already created for you and put this into it:

3. Use the same Notice style: https://github.com/reactioncommerce/reaction-docs/blob/master/developer/how-to-change-the-favicon.md#notice

```
### Notice

You also could omit ...
```

And then we can merge this once Release 1.8 is released.

**Comment by machikoyasuda** [comment]
Ready and will merge with 1.8

**Pull request merged**
