### PR TITLE
 Add new Navbar to Core Layout Example 

### PR DESCRIPTION
**Pull request by glmaljkovich**
Since we are not making any new header while in this tutorial it's better to add the Navbar Component otherwise the user won't be able to login and navigate the tags.

- Added the navbar
- Updated the imports
- Fixed some typos
- removed the "headerLayout" from `register.js`

### CODE REVIEW

**Comment by glmaljkovich** [comment]
Fixed Merge conflict.

**Comment by machikoyasuda** [comment]
Thank you @glmaljkovich for these updates! We're finally working on updating the tutorial now, thanks to @prinzdezibel.

**Comment by prinzdezibel** [comment]
This PR partially overlaps with #346, but merge conflicts should be easy to fix.

**Comment by prinzdezibel** [comment]
@zenweasel I think this one is superseded.

**Comment by zenweasel** [comment]
@glmaljkovich Thanks so much for this PR. @prinzdezibel has put in a bunch of work revamping the example plugin and getting it up to date so I think he may have taken care of this issue. Let us know if you see any other issues with the example plugin and thanks again for contributing. I really appreciate it.
🎉 🎉 🎉

**Pull request closed without merging**
