### PR TITLE
fix: add stance on Windows development support

### LINKED ISSUE #731: Update content for Windows support
https://docs.reactioncommerce.com/docs/installation-reaction-platform#docsNav
image

Replace with this content:
**Windows:** Reaction does not officially support development on Windows currently. 
Development on Windows may be possible, but is untested. We are currently unable to provide support for developers using Windows.

### PR DESCRIPTION
**Pull request by spencern**
Resolves #731 
Impact: **major**  
Type: **docs**

## Issue
Developing Reaction Commerce in a Windows environment has been difficult. Because the development environment is containerized, in theory development in Windows should be straightforward. In practice, there has been difficulty developing in Windows. As we are unable to support development in Windows, we’re updating our installation docs to show that.

We’d like to be able to support development in Windows and plan to revisit the policy when we can spend time troubleshooting the issues that are found in the Windows environment. 

PRs to address issues related to development in the Windows environment are welcomed!

## Solution & Screenshots
Adjust Windows support policy in installation docs. 

## Breaking changes
n/a

## Testing
1. Check that the installation docs reflect our new support policy on Windows as presented by @cshivaratri in #731

### CODE REVIEW

**Comment by cshivaratri** [comment]
@spencern I will get to this end of day today after court duty.

**Comment by spencern** [comment]
@machikoyasuda good question, and thanks for highlighting that section of the documentation.
@cshivaratri I'd be interested in your opinion on this.

My opinion is that we only support 2.x going forward with the exception of critical severity security issues which we'll support in 1.x through June of this year per our blog post here: https://blog.reactioncommerce.com/the-road-ahead-product-updates-october-2018/

With that being the case, I don't think we should indicate that we support that version, but we could point Windows users at it as the most recent version of Reaction that we've known to work on Windows. I don't think that's a great option either, but it may be better than nothing.

**Comment by cshivaratri** [comment]
@spencern so to clarify, you are suggesting that for Mac users, we will support only 2.x going forward, except for security issues. And for Windows users we point to the version we've known it to work on? This goes to the discussion we had earlier about taking stock of areas that need immediate update on the docs site - I have a list that I will share tomorrow and will include this as part of it. Let me look through the list and other suggestions can revert back on this.

**Comment by spencern** [comment]
@cshivaratri @machikoyasuda 
Thinking about it more, I don't think our docs should point users at older versions of Reaction, even for Windows users. I think it will create more problems than it solves. 
- It won't help Windows users get any closer to using the 2.x versions of Reaction 
- It will create some unique migration situations for Windows users who later want to update to 2.x
- It gives the appearance that it's a "recommended solution" when we will not actually support it.

I think it would be better to state that we don't support development in Windows at this time and leave it at that.

**Comment by machikoyasuda** [comment]
LGTM 👍 We can just leave the 1.16 and previous Windows instructions for now. Sometime in the future we _could_ just remove all previous versions, but that's not necessary right now.

**Comment by cshivaratri** [comment]
Agree @spencern

**Pull request merged**
