### PR TITLE
chore: linting

### LINKED ISSUE #454: [Chore]: Enforce remark-lint in PRs

### PR DESCRIPTION
**Pull request by machikoyasuda**
closes #454 

Run: `npm run lint`

Undoes one rule, allowing mixed case for file names.

### CODE REVIEW

**Comment by zenweasel** [comment]
Are we sure about all these rules?

**Comment by machikoyasuda** [comment]
@zenweasel I just based it off the rules that were already in place. I'm all for it for consistency sake. 

The ones we use:
https://github.com/remarkjs/remark-lint/tree/master/packages/remark-preset-lint-consistent
https://github.com/remarkjs/remark-lint/tree/master/packages/remark-preset-lint-recommended

The most extreme one:
https://github.com/remarkjs/remark-lint/tree/master/packages/remark-preset-lint-markdown-style-guide

**Comment by zenweasel** [comment]
Ok, your call but the "don't use underscores for italics" seemed weird to me

**Comment by machikoyasuda** [comment]
Closing so I can undo the Italics/Md rule

**Pull request closed without merging**
