### PR TITLE
Fix for issue #355

### PR DESCRIPTION
**Pull request by prinzdezibel**
FAQ: How do I add HTML/markup to my product descriptions?

### CODE REVIEW

**Comment by prinzdezibel** [comment]
@spencern Would you mind to have a quick look into it? Any suggestions how to do it better? Thank you!

**Comment by prinzdezibel** [comment]
I'd definitely also be fine with leaving out the last part and just go with your statements.

**Comment by spencern** [comment]
I think it would be fine to suggest that if you want to deal with that you can use `replaceComponent` but maybe we don't go so far as to suggest exactly how to use `dangerouslySetInnerHTML`

**Comment by prinzdezibel** [comment]
That's good, I like that.

**Comment by machikoyasuda** [comment]
👍

**Comment by prinzdezibel** [comment]
Done.

**Comment by spencern** [comment]
@prinzdezibel I've approved, but you've got conflicts now.

**Comment by prinzdezibel** [comment]
done.

**Pull request merged**
