### PR TITLE
FAQ: Changing favicon - Closes issue #359

### PR DESCRIPTION
**Pull request by prinzdezibel**
Answer to FAQ: How to change the favicon?

### CODE REVIEW

**Comment by prinzdezibel** [comment]
@jshimko Thanks for the hint concerning the favicons.js
Would you mind to have a quick look into this FAQ?

**Comment by prinzdezibel** [comment]
@jshimko If you can't find time ATM because of your other tasks, let me know.

**Comment by jshimko** [comment]
Should we maybe consider making it configurable so people don't need to go copy/paste some code and end up with a duplicate set of favicons in their `<head>`?  Maybe something like `Meteor.settings.public.faviconBasePath`. They'd still have to generate the assets, but at least they wouldn't have to create a plugin, write duplicate code, and end up with duplicate favicons in the header.  I figure that should only be a single line of code to add that.

So this line...

https://github.com/reactioncommerce/reaction/blob/master/imports/plugins/included/default-theme/client/favicons.js#L8

becomes something like...

```js
const basePath = Meteor.settings.public.faviconBasePath || "https://assets.reactioncommerce.com/favicon/";
```

Then users could easily put them anywhere in the app or on a CDN without any additional code.  That also allows you to set it via the `METEOR_SETTINGS` environment variable.

**Comment by zenweasel** [comment]
I don't know what the use case is for people wanting to not customize anything else about their shop except for the favicon, I think that's going to be rare. But I am still up for making this something they can more easily customize like we do with the brand icon. Let's open a separate ticket for that and put this one in now?

**Comment by zenweasel** [comment]
Also, this is another item that seems wrongly in the admin section. I think the idea is that admins are not creating plugins so I don't think that should be something we suggest to them. If it can't be done through the dashboard let's not put it in the admin FAQ.

**Comment by prinzdezibel** [comment]
@zenweasel  Actually, I was not aware of having two FAQs section until this morning when I've read a note from @machikoyasuda. I'm going to move it to the Developer's FAQ.

**Comment by prinzdezibel** [comment]
@zenweasel could you please have a quick look before I'll resolve the conflicts? thanks.

**Comment by prinzdezibel** [comment]
@zenweasel should be ok from my side.

**Comment by zenweasel** [comment]
@prinzdezibel You still have conflicts here

**Comment by prinzdezibel** [comment]
Navigation was missing.

**Pull request merged**
