### PR TITLE
docs: new breaking changes article

### PR DESCRIPTION
**Pull request by aldeed**
Impact: **minor**  
Type: **docs**

A new article about breaking changes in Reaction (and in general).

### CODE REVIEW

**Comment by aldeed** [comment]
This was mostly a brain dump with some minimal editing and rearranging after, so it feels a bit disorganized to me. In addition to a good editor, it could probably use some code examples showing a breaking change and a non-breaking alternative, but I didn't have time to find good examples. Feel free to commit edits and additions on this branch before we merge it.

**Comment by aldeed** [comment]
Also deployed to staging for easier reading: https://reaction-docs-staging.reactioncommerce.com/docs/devs-breaking-changes

**Comment by machikoyasuda** [comment]
Whoa this is great. This should be required reading for all of us!

**Comment by machikoyasuda** [comment]
As we move forward, it would be great if we add links to examples of specific Pull Requests and code before/after changes showing examples of how to deprecate something, how to identify/avoid breaking changes in plugins and functions.

**Comment by aldeed** [comment]
I merged this since it has two approvals, but I still welcome PRs to edit and add examples when people have more time.

**Pull request merged**
