### PR TITLE
(fix) Update prerender guide

### PR DESCRIPTION
**Pull request by ajporlante**
If https://github.com/reactioncommerce/reaction/pull/4331 gets merged, then the docs on prerender have to be updated as suggested in this PR.

### CODE REVIEW

**Comment by machikoyasuda** [comment]
Thank you @ajporlante! I'll merge this either into master or Release 1.13, whichever it ends up going out into.

**Comment by spencern** [comment]
@machikoyasuda did this end up going out in v1.13.0 or scheduled for 1.14.0?

**Comment by machikoyasuda** [comment]
@spencern It's not out yet. Waiting on 1.14 for reaction!

**Comment by spencern** [comment]
@machikoyasuda should we create a `release-1.14.0` branch on docs?

**Pull request merged**
