### PR TITLE
Add vulnerability reporting instructions

### PR DESCRIPTION
**Pull request by aaronjudd**
Add security reporting instructions. (Send to email group). Adds to testing nav.

### CODE REVIEW

**Comment by machikoyasuda** [comment]
LGTM 👍  Any thoughts @spencern?

**Comment by zenweasel** [comment]
Did we decide how people would be notified of a security release? The probably need something to let people know that an upgrade is **required**.

**Comment by spencern** [comment]
LGTM as well. 👍

**Comment by spencern** [comment]
@zenweasel I agree, but not sure that needs to be part of this PR

**Comment by aaronjudd** [comment]
@zenweasel I couldn't decided on an appropriate mechanism, and I feel like, we're not going to notifying about a patch until we release it, are we? so Github notifications, emails, do serve that point.  I was looking for a way to have a robot to create an issue on forks.. that'd really do the trick, but that's a bit extreme for today.

**Comment by zenweasel** [comment]
If I am a store manager happily using my code, I may not really pay attention to normal release stuff or at least give it the attention it requires. I guess even if we had some sort of release notification process where we could just flag something as a security release.

If we start doing lots of small releases (like we hope to) then people will probably start paying less attention to each particular announcement.

I don't think figuring that out needs to hold up this PR though. Just don't want it to get forgotten.

**Comment by aaronjudd** [comment]
@zenweasel yes, agree seem like the only sure fire way would be to notify in-app.

**Comment by spencern** [comment]
Agreed that we should figure out a way to notify existing operators,

Worth a discussion for how to do this self installs vs platform.

**Pull request merged**
