### PR TITLE
docs: switch bin/token instructions to hydra-token, fix env variable table width

### LINKED ISSUE #906: Environment variables documentation HTML table is unreadable
Type: **minor**

**Describe the bug**

We have used an HTML table to organize our documentation around environment variables. This material has far too many long words and paragraphs to be readable in a table. The word wrapping becomes absurd.

**To Reproduce**

https://docs.reactioncommerce.com/docs/environment-variables

**Expected behavior**

Please just use headers, paragraphs, etc.

**Screenshots**
screen-2020-02-19-15:53:51-env-var-docs-table

### PR DESCRIPTION
**Pull request by aldeed**
Resolves #906 
Type: **docs**

- Update all mentions of `bin/token` to new `hydra-token` CLI instructions
- Fix the table column width on the Environment Variables page. The table content has not changed. To fix them, I copied the generated `<table>` HTML into the markdown files and added `min-width` style on each column header.

## Testing
`docker-compose up`, go to http://localhost:4242/docs/environment-variables, and verify that the tables extend beyond the width of the content area and are visible by scrolling horizontally. All table cell content should be readable.

### CODE REVIEW

**Review by focusaurus — APPROVED** [review]
Is it possible to do the table min-width CSS change in a CSS file and keep the markdown table? I'd still rather see paragraphs and believe this is not naturally tabular data but this will help a lot so thanks for the change!

**Comment by aldeed** [comment]
@focusaurus No, not that I could figure out. The markdown parser doesn't support any way of adding a class (or any attributes) to tables, and reliably selecting it in CSS without a class did not seem easy. We could do the min-width with CSS _keeping_ the tables as HTML. That seems unnecessary to me, but either way.

**Comment by focusaurus** [comment]
Only untested idea I have would be a hack like:

```md 
<div id="env-vars">
<style>
div#env-vars th { min-width: 300px }
</style>

...markdown table goes here...
| `GRAPHQL_INTROSPECTION_ENABLED`                  | Allow introspection of the GraphQL API.                                                                                                                                              | Because `NODE_ENV` is "development", defaults to `true`. Set to `false` in `.env` to override.                                                                               | Because `NODE_ENV` is "production", defaults to `false`. Set to `true` to override.                                                                                                 |
</div>
```

???

Dunno just spitballing hacks.

**Comment by aldeed** [comment]
@focusaurus That does indeed work. See [revised commit](https://github.com/reactioncommerce/reaction-docs/pull/917/commits/1c58215d3ef7576ba4e0b81de9dbe2cebb9de271). Good to merge?

**Review by focusaurus — APPROVED** [review]

**Pull request merged**
