### PR TITLE
Improve RC docs.

### PR DESCRIPTION
**Pull request by foladipo**

### CODE REVIEW

**Comment by zenweasel** [comment]
@foladipo PR's should be submitted to `development` rather than `master`.

**Comment by foladipo** [comment]
Thanks. I've changed the base branch.

**Comment by machikoyasuda** [comment]
Hi @foladipo - thanks for your updates! Looks good to me.

**Comment by zenweasel** [comment]
@foladipo this is still marked WIP. If you are done this is ready to merge I think.

**Comment by foladipo** [comment]
@zenweasel @machikoyasuda Yes, I'm done with the changes I wish to make. I've unmarked this PR as WIP too.

**Pull request merged**
