### PR TITLE
Add Developer FAQ

### PR DESCRIPTION
**Pull request by zenweasel**
A placeholder for capturing answers to developers FAQ from Gitter, Forums, etc.

### CODE REVIEW

**Comment by machikoyasuda** [comment]
Thanks for getting this started Brent 🎊 

Maybe we could add a last question like this:

```
I have another question. Where's the best place to ask it?

You can post questions in Gitter chat about Installation, Deployment, general Reaction topics and Architecture. You can also post questions in the Forums.

Want more help? You can also ask a question live during our Community Calls. Here's the past agendas: https://docs.google.com/document/d/1PwenrammgQJpQfFoUUJZ96i_JJYCM_4glAjB1_ZzgwA/edit and a form to submit questions to be discussed at the calls: https://docs.google.com/forms/d/e/1FAIpQLSfsNNH1W4bP7k4Gkl1JYF4vCEwQcHE9X3OIFfTH2TNwD7dN4Q/viewform
```

**Comment by zenweasel** [comment]
Yeah, that's good. Should those Gitter mentions link to the channels?

**Comment by machikoyasuda** [comment]
A question to add: https://forums.reactioncommerce.com/t/calling-plugin-and-server-code-from-a-package/626

**Comment by zenweasel** [comment]
@machikoyasuda I think the best approach may be to just get this original template in and open PR's for all additional questions. We can maybe even open the PR w/o an answer to have a way to capture them?

**Pull request merged**
